---
ID: "f2a9410d-7a45-58d5-ae83-3831686b6b55"
Parent: "dfbd6bd1-f3bf-5fc8-b737-a46d5f216eaf"
Template: "dfbd6bd1-f3bf-5fc8-b737-a46d5f216eaf"
Path: "/sitecore/templates/Project/poc/Styleguide-SitecoreContext/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220506T182953Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5c1b20de-9317-44cd-ae0b-9c4cf32ded09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220506T182953Z
