---
ID: "774c192e-851b-5ec0-b24c-9ad06b4ad8c7"
Parent: "69e04d3b-d18b-5ca8-ad2d-236c48eb474d"
Template: "69e04d3b-d18b-5ca8-ad2d-236c48eb474d"
Path: "/sitecore/templates/Project/poc/Styleguide-FieldUsage-Image/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220506T182948Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a968d544-0d4b-48c4-976e-4248f5432f7d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220506T182948Z
