---
ID: "0b87b688-ed2c-581d-a57f-03fb952a9301"
Parent: "ff6cf7ce-6508-5204-a7fb-d234769db9c2"
Template: "ff6cf7ce-6508-5204-a7fb-d234769db9c2"
Path: "/sitecore/templates/Project/poc/Styleguide-FieldUsage-File/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220506T182948Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e50dc2fb-ac81-4c44-ad52-03b35b9e77cf"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220506T182948Z
