---
ID: "517bcb9c-d55e-58f5-b543-b35aa7391c0d"
Parent: "fccb7166-13f1-517e-8e0a-bfe10d96e711"
Template: "fccb7166-13f1-517e-8e0a-bfe10d96e711"
Path: "/sitecore/templates/Project/poc/Styleguide-FieldUsage-Checkbox/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220506T182946Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\JssImport
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eb0838b7-ad68-4c4e-972a-c9b5d29b923c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\JssImport
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220506T182946Z
